spring:
  config:
    import: optional:secret.properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email-address}
    password: ${email-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true